version: "3.6"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  php-fpm:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./:/var/www/html"
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - DATABASE_TYPE=mysql
      - DATABASE_USER=rabbitmq-user
      - DATABASE_PASSWORD=rabbitmq-password
      - DATABASE_NAME=rabbitmq-db
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
  mysql:
    build:
      context: .docker/mysql
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
